# Generated by Django 6.0 on 2026-01-11 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleswoman',
            name='administrator_id',
        ),
        migrations.AddField(
            model_name='saleswoman',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.administrator'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='role',
            field=models.CharField(choices=[('admin', 'administrator'), ('saleswoman', 'Saleswoman')], default='admin', max_length=30),
        ),
        migrations.AlterField(
            model_name='saleswoman',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='saleswoman',
            name='role',
            field=models.CharField(choices=[('admin', 'administrator'), ('saleswoman', 'Saleswoman')], default='saleswoman', max_length=30),
        ),
        migrations.AlterField(
            model_name='saleswoman',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
