# Generated by Django 6.0 on 2026-01-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_saleswoman_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleswoman',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
