# Generated by Django 6.0 on 2026-01-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_saleswoman_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'administrador'), ('VENDEDORA', 'vendedora')], default='VENDEDORA', max_length=25),
        ),
    ]
