# Generated by Django 6.0 on 2026-01-15 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_saleswoman_administrator_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fabric_Type_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('material_type', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric_Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_Scrap_id', models.IntegerField(unique=True)),
                ('length_meters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width_meters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('historial_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_scraps', to='users.administrator')),
                ('saleswoman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_scraps', to='users.saleswoman')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps_type', to='inventory.fabric_type')),
            ],
        ),
    ]
