# Generated by Django 6.0 on 2026-01-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_fabric_scrap_administrator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric_type',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
