# Generated by Django 6.0 on 2026-01-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_fabric_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric_scrap',
            name='fabric_Scrap_id',
        ),
        migrations.RemoveField(
            model_name='fabric_scrap',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fabric_type',
            name='id',
        ),
        migrations.AlterField(
            model_name='fabric_type',
            name='Fabric_Type_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='fabric_scrap',
            name='fabric_scrap_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
