# Generated by Django 6.0 on 2026-01-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_fabric_scrap_fabric_scrap_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric_type',
            name='material_type',
            field=models.CharField(max_length=150),
        ),
    ]
