# Generated by Django 6.0 on 2026-01-18 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_fabric_scrap_length_meters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric_scrap',
            name='historial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
