# Generated by Django 6.0 on 2026-01-18 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_fabric_scrap_historial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric_scrap',
            name='historial_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
