# Generated by Django 6.0 on 2026-01-19 01:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_fabric_scrap_historial_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric_scrap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_scraps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabric_scrap',
            name='created_by_role',
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabric_type',
            name='price_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio por metro', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='fabric_type',
            name='last_update_at',
            field=models.DateTimeField(auto_now=True, help_text='Se actualiza cuando hay una modificación'),
        ),
        migrations.AlterField(
            model_name='fabric_type',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Se actualiza cuando se agrega un nuevo registro'),
        ),
    ]
