# Generated by Django 6.0 on 2026-01-21 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_fabric_scrap_created_by_fabric_scrap_created_by_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric_scrap',
            name='qr',
            field=models.CharField(blank=True, help_text='Código QR asociado al retazo', max_length=250),
        ),
        migrations.AddField(
            model_name='fabric_type',
            name='qr',
            field=models.CharField(blank=True, help_text='Código QR asociado al tipo de tela', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fabric_scrap',
            name='active',
            field=models.BooleanField(default=True, help_text='Indica si el retazo está disponible'),
        ),
        migrations.AlterField(
            model_name='fabric_scrap',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción opcional del retazo'),
        ),
        migrations.AlterField(
            model_name='fabric_scrap',
            name='fabric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scraps_type', to='inventory.fabric_type'),
        ),
        migrations.AlterField(
            model_name='fabric_scrap',
            name='historial_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio histórico al momento de la creación del retazo', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='fabric_scrap',
            name='sale_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se vendió el retazo', null=True),
        ),
    ]
