# Generated by Django 6.0 on 2026-01-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_fabric_scrap_qr_fabric_type_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric_scrap',
            name='qr',
            field=models.CharField(blank=True, help_text='Código QR asociado al retazo', max_length=250, null=True),
        ),
    ]
