# Generated by Django 6.0 on 2026-01-21 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_fabric_scrap_length_meters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric_scrap',
            name='length_meters',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.14)]),
        ),
        migrations.AlterField(
            model_name='fabric_scrap',
            name='width_meters',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.14)]),
        ),
    ]
