# Generated by Django 6.0 on 2026-01-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='administrador',
            new_name='administrator',
        ),
    ]
