# Generated by Django 6.0 on 2026-01-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_rename_administrador_record_administrator'),
        ('users', '0002_remove_saleswoman_administrator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_acciones', to='users.administrator'),
        ),
    ]
