# Generated by Django 6.0 on 2026-02-08 21:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_record_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Creacion'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación Física'), ('DEACTIVATE', 'Desactivación (Borrado Lógico)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='new_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='old_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
