# Generated by Django 6.0 on 2026-01-25 19:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dollar_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Fuente de la tasa de cambio', max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tasa de cambio del dólar', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización de la tasa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
            ],
        ),
    ]
